model_name: CatBoost_transformer

module_name: "catboost"
class_name: "CatBoostClassifier"

params:
  classifier__iterations: 50
  classifier__depth: 3
  classifier__logging_level: 'Silent'
  classifier__task_type: 'GPU' # 'CPU' 
