model_name: CatBoost_transformer

module_name: "catboost"
class_name: "CatBoostClassifier"

params:
  iterations: [100, 500, 1000]
  depth: [2, 3, 5]
  logging_level: ['Silent']
  task_type: ['CPU'] # GPU 
